// Большой каталог товаров из российских магазинов (цены приблизительные, актуальные на момент написания).
// Цены хранятся в КОПЕЙКАХ — это позволяет избежать float-погрешностей.

export type SeedProduct = {
  id: string;
  title: string;
  brand: string;
  storeId: string;
  storeUrl: string;
  price: number; // копейки
  originalPrice?: number;
  currency?: string;
  categoryId: string;
  image: string;
  color?: string;
  tags?: string[];
  description: string;
};

export const SEED_CATEGORIES = [
  { id: "tech", label: "Техника", emoji: "◎" },
  { id: "fashion", label: "Мода", emoji: "◇" },
  { id: "home", label: "Дом", emoji: "◈" },
  { id: "beauty", label: "Красота", emoji: "✦" },
  { id: "books", label: "Книги", emoji: "☰" },
  { id: "outdoors", label: "Спорт", emoji: "△" },
  { id: "kitchen", label: "Кухня", emoji: "◐" },
  { id: "music", label: "Музыка", emoji: "♫" },
  { id: "kids", label: "Детям", emoji: "✿" },
  { id: "gaming", label: "Игры", emoji: "◆" },
];

export const SEED_STORES = [
  { id: "ym", name: "Яндекс Маркет", website: "https://market.yandex.ru" },
  { id: "ozon", name: "OZON", website: "https://www.ozon.ru" },
  { id: "wb", name: "Wildberries", website: "https://www.wildberries.ru" },
  { id: "dns", name: "DNS", website: "https://www.dns-shop.ru" },
  { id: "mvideo", name: "М.Видео", website: "https://www.mvideo.ru" },
  { id: "citilink", name: "Ситилинк", website: "https://www.citilink.ru" },
  { id: "megamarket", name: "Мегамаркет", website: "https://megamarket.ru" },
  { id: "restore", name: "re:Store", website: "https://re-store.ru" },
  { id: "lamoda", name: "Lamoda", website: "https://www.lamoda.ru" },
  { id: "sportmaster", name: "Спортмастер", website: "https://www.sportmaster.ru" },
  { id: "goldapple", name: "Золотое Яблоко", website: "https://goldapple.ru" },
  { id: "hoff", name: "Hoff", website: "https://hoff.ru" },
  { id: "ikea", name: "IKEA (Дивано)", website: "https://www.divano.ru" },
  { id: "chitaigorod", name: "Читай-город", website: "https://www.chitai-gorod.ru" },
  { id: "labirint", name: "Лабиринт", website: "https://www.labirint.ru" },
  { id: "podpisnie", name: "Подписные издания", website: "https://podpisnie.ru" },
  { id: "tastycoffee", name: "Tasty Coffee", website: "https://tastycoffee.ru" },
  { id: "pult", name: "Pult.ru", website: "https://www.pult.ru" },
  { id: "mirkubikov", name: "Мир Кубиков", website: "https://mir-kubikov.ru" },
  { id: "onyxboox", name: "ONYX BOOX", website: "https://onyxboox.ru" },
  { id: "detmir", name: "Детский мир", website: "https://www.detmir.ru" },
  { id: "letoile", name: "Л'Этуаль", website: "https://www.letu.ru" },
  { id: "respublika", name: "Республика", website: "https://www.respublica.ru" },
  { id: "steam", name: "Steam", website: "https://store.steampowered.com" },
  { id: "epic", name: "Epic Games", website: "https://store.epicgames.com" },
  { id: "mytoys", name: "MyToys", website: "https://www.mytoys.ru" },
];

export const SEED_PRODUCTS: SeedProduct[] = [
  // ===== TECH (20) =====
  {
    id: "p_station_mini_2",
    title: "Умная колонка Яндекс Станция Мини 2 с часами",
    brand: "Яндекс",
    storeId: "ym",
    storeUrl:
      "https://market.yandex.ru/search?text=%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81+%D0%A1%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D1%8F+%D0%9C%D0%B8%D0%BD%D0%B8+2",
    price: 799000,
    originalPrice: 999000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1589003077984-894e133dabab?auto=format&fit=crop&w=1200&q=80",
    color: "#2e2e2e",
    tags: ["Алиса", "Zigbee"],
    description:
      "Компактная колонка с Алисой, часами и Zigbee‑хабом — управляет умным домом и будит по утрам.",
  },
  {
    id: "p_airpods_pro_2",
    title: "Наушники Apple AirPods Pro (2-го поколения) с USB-C",
    brand: "Apple",
    storeId: "restore",
    storeUrl: "https://re-store.ru/catalog/airpods/airpods-pro/",
    price: 2299000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=1200&q=80",
    color: "#F2F2F2",
    tags: ["ANC", "Spatial Audio"],
    description: "Адаптивный звук, чип H2 и удобный зарядный кейс с USB‑C. Любимые беспроводные наушники на каждый день.",
  },
  {
    id: "p_sony_wh1000xm5",
    title: "Беспроводные наушники Sony WH-1000XM5",
    brand: "Sony",
    storeId: "dns",
    storeUrl: "https://www.dns-shop.ru/search/?q=sony+wh-1000xm5",
    price: 4299900,
    originalPrice: 4999000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=1200&q=80",
    color: "#111",
    tags: ["ANC", "30 ч"],
    description: "Флагманское шумоподавление Sony с восемью микрофонами и самыми мягкими амбушюрами в линейке.",
  },
  {
    id: "p_iphone_15_pro",
    title: "Смартфон Apple iPhone 15 Pro 256 ГБ, титан натуральный",
    brand: "Apple",
    storeId: "restore",
    storeUrl: "https://re-store.ru/catalog/iphone/iphone-15-pro/",
    price: 11999000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1696446702248-a26ec6c7c66e?auto=format&fit=crop&w=1200&q=80",
    color: "#c8bfa5",
    tags: ["A17 Pro", "Титан"],
    description: "Титановый корпус, Action Button, камера на 48 МП и вся мощь чипа A17 Pro. Флагман, на который меняют старый iPhone.",
  },
  {
    id: "p_xiaomi_redmi_note",
    title: "Смартфон Xiaomi Redmi Note 13 Pro 8/256 ГБ",
    brand: "Xiaomi",
    storeId: "citilink",
    storeUrl: "https://www.citilink.ru/search/?text=xiaomi%20redmi%20note%2013%20pro",
    price: 2499000,
    originalPrice: 2999000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
    color: "#3a3a3a",
    tags: ["200 МП", "AMOLED 120 Гц"],
    description: "Матрица на 200 МП, быстрый AMOLED 120 Гц и зарядка 67 Вт за вменяемые деньги.",
  },
  {
    id: "p_macbook_air_m3",
    title: "Ноутбук Apple MacBook Air 13\" M3 8/256 ГБ, серебристый",
    brand: "Apple",
    storeId: "restore",
    storeUrl: "https://re-store.ru/catalog/mac/macbook-air/",
    price: 12499000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    color: "#d8d9dc",
    tags: ["M3", "18 ч"],
    description: "Самый тонкий MacBook Air с чипом M3 — тихий, холодный и честно держит день.",
  },
  {
    id: "p_onyx_palma",
    title: "Электронная книга ONYX BOOX Palma 2",
    brand: "ONYX BOOX",
    storeId: "onyxboox",
    storeUrl: "https://onyxboox.ru/palma-2",
    price: 3499000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?auto=format&fit=crop&w=1200&q=80",
    color: "#1b1b1d",
    tags: ["6.13\"", "Android"],
    description: "Компактная читалка в форм‑факторе смартфона: E‑Ink, Android и полноценный браузер в кармане.",
  },
  {
    id: "p_fujifilm_xt30",
    title: "Фотоаппарат Fujifilm X-T30 II Kit 15–45mm",
    brand: "Fujifilm",
    storeId: "mvideo",
    storeUrl: "https://www.mvideo.ru/product-list-page?q=fujifilm+x-t30+ii",
    price: 9999000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1606986601547-b0e2f8d14f0f?auto=format&fit=crop&w=1200&q=80",
    color: "#b7b7b7",
    tags: ["26 МП", "X-Trans"],
    description: "Беззеркалка с легендарной плёночной цветопередачей Fuji. Лёгкая, красивая, влезает в рюкзак.",
  },
  {
    id: "p_instax_mini",
    title: "Плёночный фотоаппарат Fujifilm Instax Mini 12",
    brand: "Fujifilm",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=instax+mini+12",
    price: 799000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1495707902641-75cac588d2e9?auto=format&fit=crop&w=1200&q=80",
    color: "#a9c7ef",
    tags: ["Авто-экспозиция"],
    description: "Навёл, повернул объектив — и получил крошечную распечатку вечера до того, как он закончился.",
  },
  {
    id: "p_ipad_air",
    title: "Планшет Apple iPad Air 11\" M2 128 ГБ Wi-Fi, серый космос",
    brand: "Apple",
    storeId: "restore",
    storeUrl: "https://re-store.ru/catalog/ipad/ipad-air/",
    price: 6999000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=1200&q=80",
    color: "#606061",
    tags: ["M2", "11\""],
    description: "Чип M2, поддержка Apple Pencil Pro и Magic Keyboard. Планшет, который всё чаще заменяет ноутбук.",
  },
  {
    id: "p_apple_watch_se",
    title: "Умные часы Apple Watch SE 2 44 мм, серебристый",
    brand: "Apple",
    storeId: "restore",
    storeUrl: "https://re-store.ru/catalog/apple-watch/apple-watch-se/",
    price: 3299000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=1200&q=80",
    color: "#dcdcdc",
    tags: ["GPS", "44 мм"],
    description: "Все важные умные функции Apple Watch без лишних сенсоров. Честные две зарядки за ночь.",
  },
  {
    id: "p_marshall_major",
    title: "Наушники Marshall Major V Black",
    brand: "Marshall",
    storeId: "ym",
    storeUrl: "https://market.yandex.ru/search?text=marshall+major+v",
    price: 1599000,
    originalPrice: 1899000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=1200&q=80",
    color: "#111",
    tags: ["100 ч", "Bluetooth 5.3"],
    description: "Рокерский классика: фирменная текстура, джойстик и 100 часов автономной работы.",
  },
  {
    id: "p_huawei_matepad",
    title: "Планшет HUAWEI MatePad 11.5 S, 8/256 ГБ",
    brand: "HUAWEI",
    storeId: "mvideo",
    storeUrl: "https://www.mvideo.ru/product-list-page?q=huawei+matepad+11.5",
    price: 3999000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=1200&q=80",
    color: "#2b2b2b",
    tags: ["2.8K", "144 Гц"],
    description: "Яркий 2.8K‑экран, 144 Гц и поддержка стилуса M‑Pencil. Отличная рабочая лошадка для заметок.",
  },
  {
    id: "p_kindle_11",
    title: "Электронная книга Amazon Kindle 11 2022",
    brand: "Amazon",
    storeId: "ym",
    storeUrl: "https://market.yandex.ru/search?text=amazon+kindle+11+2022",
    price: 1299000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?auto=format&fit=crop&w=1200&q=80",
    color: "#1b1b1d",
    tags: ["6\"", "USB-C"],
    description: "Простая и лёгкая читалка с чётким экраном и USB‑C. Влезает в любую сумку.",
  },
  {
    id: "p_jbl_clip_5",
    title: "Портативная колонка JBL Clip 5",
    brand: "JBL",
    storeId: "dns",
    storeUrl: "https://www.dns-shop.ru/search/?q=jbl+clip+5",
    price: 599000,
    originalPrice: 799000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1200&q=80",
    color: "#1b3f6b",
    tags: ["IP67", "12 ч"],
    description: "Маленький, пристёгивается карабином. Идеальная колонка для похода и пляжа.",
  },
  {
    id: "p_rog_ally_x",
    title: "Портативная консоль ASUS ROG Ally X 24/1 ТБ",
    brand: "ASUS",
    storeId: "dns",
    storeUrl: "https://www.dns-shop.ru/search/?q=asus+rog+ally",
    price: 9999000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1640955011254-39734e60b16f?auto=format&fit=crop&w=1200&q=80",
    color: "#1a1a1a",
    tags: ["Windows", "120 Гц"],
    description: "Портативный Windows‑ПК в форм‑факторе Switch. 24 ГБ памяти и долгая батарея.",
  },
  {
    id: "p_tp_link_deco",
    title: "Mesh-система TP-Link Deco X50, 3 шт.",
    brand: "TP-Link",
    storeId: "citilink",
    storeUrl: "https://www.citilink.ru/search/?text=tp-link+deco+x50",
    price: 1799000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1558403194-611308249627?auto=format&fit=crop&w=1200&q=80",
    color: "#eaeaea",
    tags: ["Wi-Fi 6", "AX3000"],
    description: "Три точки, бесшовная сеть на всю квартиру. Настраивается с телефона за пять минут.",
  },
  {
    id: "p_philips_hue",
    title: "Умная лампа Philips Hue White and Color E27",
    brand: "Philips",
    storeId: "ym",
    storeUrl: "https://market.yandex.ru/search?text=philips+hue+e27+white+color",
    price: 499000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1565636291693-5f3e82c25c75?auto=format&fit=crop&w=1200&q=80",
    color: "#ffe6b3",
    tags: ["16 млн цветов"],
    description: "Колба Hue, которую можно покрасить в любой оттенок — от янтарного утра до зелёного кино‑вечера.",
  },
  {
    id: "p_logitech_mxm3",
    title: "Мышь беспроводная Logitech MX Master 3S",
    brand: "Logitech",
    storeId: "citilink",
    storeUrl: "https://www.citilink.ru/search/?text=logitech+mx+master+3s",
    price: 1099000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=1200&q=80",
    color: "#2d2d2d",
    tags: ["8000 dpi", "Bluetooth"],
    description: "Флагманская мышь Logitech: магнитное колесо, 70 дней автономности и абсолютно бесшумные клики.",
  },
  {
    id: "p_keychron_k3",
    title: "Клавиатура Keychron K3 Pro Wireless, Brown Switch",
    brand: "Keychron",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=keychron+k3+pro",
    price: 1299000,
    categoryId: "tech",
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=80",
    color: "#2a2a2a",
    tags: ["Low-profile", "QMK/VIA"],
    description: "Низкопрофильная механика для Mac и Windows. Мягкие коричневые свитчи и знакомая раскладка.",
  },

  // ===== FASHION (15) =====
  {
    id: "p_nb_574",
    title: "Кроссовки New Balance 574 Core",
    brand: "New Balance",
    storeId: "lamoda",
    storeUrl: "https://www.lamoda.ru/c/715/shoes-newbalance/",
    price: 1299900,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1200&q=80",
    color: "#dce7ef",
    tags: ["Замша"],
    description: "Бессмертный силуэт конца 80‑х. Замша, ENCAP‑подошва и бесконечная совместимость с любыми джинсами.",
  },
  {
    id: "p_adidas_sambaog",
    title: "Кроссовки adidas Samba OG",
    brand: "adidas",
    storeId: "lamoda",
    storeUrl: "https://www.lamoda.ru/c/15/shoes-adidasoriginals/",
    price: 1499000,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?auto=format&fit=crop&w=1200&q=80",
    color: "#ffffff",
    tags: ["Кожа", "Классика"],
    description: "Самая цитируемая модель последних двух лет. Кожа, белая подошва, замшевый мысок.",
  },
  {
    id: "p_demix_leggings",
    title: "Леггинсы женские Demix Essentials",
    brand: "Demix",
    storeId: "sportmaster",
    storeUrl: "https://www.sportmaster.ru/search/?q=demix+leggings",
    price: 249900,
    originalPrice: 329900,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=1200&q=80",
    color: "#2a2a2a",
    tags: ["Высокая посадка"],
    description: "Тянутся куда нужно, нигде не сползают. Рабочая лошадка для зала, йоги и прогулок по городу.",
  },
  {
    id: "p_uniqlo_utility_jacket",
    title: "Куртка-анорак Demix Urban Shell",
    brand: "Demix",
    storeId: "sportmaster",
    storeUrl: "https://www.sportmaster.ru/search/?q=demix+%D0%B0%D0%BD%D0%BE%D1%80%D0%B0%D0%BA",
    price: 399900,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1548883354-94bcfe321cbb?auto=format&fit=crop&w=1200&q=80",
    color: "#4a4f38",
    tags: ["DWR", "Кокетка"],
    description: "Лёгкая ветрозащита с водоотталкивающей пропиткой. Выручает, когда погода не знает, чего хочет.",
  },
  {
    id: "p_zarina_coat",
    title: "Пальто женское оверсайз Zarina",
    brand: "Zarina",
    storeId: "wb",
    storeUrl: "https://www.wildberries.ru/catalog/0/search.aspx?search=zarina+%D0%BF%D0%B0%D0%BB%D1%8C%D1%82%D0%BE+%D0%BE%D0%B2%D0%B5%D1%80%D1%81%D0%B0%D0%B9%D0%B7",
    price: 799000,
    originalPrice: 1299000,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=1200&q=80",
    color: "#c9b59a",
    tags: ["Оверсайз"],
    description: "Длинное шерстяное пальто оверсайз со спущенным плечом. Надевается поверх всего.",
  },
  {
    id: "p_levis_501",
    title: "Джинсы Levi's 501 Original Fit",
    brand: "Levi's",
    storeId: "lamoda",
    storeUrl: "https://www.lamoda.ru/c/2/shoes-levis/",
    price: 899900,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1200&q=80",
    color: "#4b6a8b",
    tags: ["Прямые", "Пуговицы"],
    description: "Оригинальный крой 501‑х с 1873 года. Выцветает красиво, вписывается куда угодно.",
  },
  {
    id: "p_tommy_hilf_tee",
    title: "Футболка Tommy Hilfiger Classic Flag",
    brand: "Tommy Hilfiger",
    storeId: "lamoda",
    storeUrl: "https://www.lamoda.ru/c/3/clothes-tommyhilfiger/",
    price: 499000,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1520975916090-3105956dac38?auto=format&fit=crop&w=1200&q=80",
    color: "#ffffff",
    tags: ["Хлопок"],
    description: "Плотный хлопок, фирменный флажок на груди. Универсальная база на каждый день.",
  },
  {
    id: "p_lime_hoodie",
    title: "Худи оверсайз Lime",
    brand: "Lime",
    storeId: "wb",
    storeUrl: "https://www.wildberries.ru/catalog/0/search.aspx?search=lime+%D1%85%D1%83%D0%B4%D0%B8",
    price: 399000,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=1200&q=80",
    color: "#c0c8c0",
    tags: ["Флис", "Плотное"],
    description: "Плотный флис, объёмный крой, ровно тот свитшот, в котором хочется жить зимой.",
  },
  {
    id: "p_marc_oplo_bag",
    title: "Сумка-шопер Marc O'Polo Canvas",
    brand: "Marc O'Polo",
    storeId: "lamoda",
    storeUrl: "https://www.lamoda.ru/c/355/bags-marcopolo/",
    price: 699000,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    color: "#c9b184",
    tags: ["Холст", "Два ремешка"],
    description: "Большой прямоугольный шопер из плотного холста. Влезает ноутбук, книги и немного продуктов.",
  },
  {
    id: "p_casio_f91",
    title: "Часы Casio F-91W-1YEG",
    brand: "Casio",
    storeId: "ym",
    storeUrl: "https://market.yandex.ru/search?text=casio+f-91w",
    price: 169900,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    color: "#151515",
    tags: ["Пластик", "Секундомер"],
    description: "Те самые электронные часы, которые носят все — от школьников до тысячелетников.",
  },
  {
    id: "p_scarf_acne",
    title: "Шарф oversize, шерсть",
    brand: "12 Storeez",
    storeId: "lamoda",
    storeUrl: "https://www.lamoda.ru/c/6/accessories-scarfs/",
    price: 799000,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1457545195570-67f207084966?auto=format&fit=crop&w=1200&q=80",
    color: "#9e8e74",
    tags: ["Шерсть", "Оверсайз"],
    description: "Толстый шерстяной шарф‑бонус с бахромой. Один раз купил — и все зимы ваши.",
  },
  {
    id: "p_panama_columbia",
    title: "Панама Columbia Bora Bora Booney",
    brand: "Columbia",
    storeId: "sportmaster",
    storeUrl: "https://www.sportmaster.ru/search/?q=columbia+bora+bora",
    price: 299900,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=1200&q=80",
    color: "#a89b74",
    tags: ["UPF 50"],
    description: "Быстро сохнет, защищает от солнца и выглядит честно туристически — как должно.",
  },
  {
    id: "p_belt_sela",
    title: "Кожаный ремень Sela Classic",
    brand: "Sela",
    storeId: "wb",
    storeUrl: "https://www.wildberries.ru/catalog/0/search.aspx?search=sela+%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D1%8C",
    price: 189900,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1624222247344-550fb60ae8c0?auto=format&fit=crop&w=1200&q=80",
    color: "#5a3825",
    tags: ["Кожа"],
    description: "Коньяковая кожа, стальная пряжка. Ремень, который не стыдно доставать из сумки.",
  },
  {
    id: "p_sunglasses_rb",
    title: "Солнцезащитные очки Ray-Ban Wayfarer Classic",
    brand: "Ray-Ban",
    storeId: "ym",
    storeUrl: "https://market.yandex.ru/search?text=ray-ban+wayfarer",
    price: 1799000,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1200&q=80",
    color: "#0d0d0d",
    tags: ["UV400"],
    description: "Архетипическая форма из 1952 года. Подходит почти любому лицу.",
  },
  {
    id: "p_ecco_boots",
    title: "Ботинки ECCO Grainer, кожа",
    brand: "ECCO",
    storeId: "lamoda",
    storeUrl: "https://www.lamoda.ru/c/715/shoes-ecco/",
    price: 1599000,
    originalPrice: 1999000,
    categoryId: "fashion",
    image: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=1200&q=80",
    color: "#3b2a1e",
    tags: ["Кожа", "GoreTex"],
    description: "Водонепроницаемые кожаные ботинки в формате «можно всё». Стерпят дождь и слякоть.",
  },

  // ===== HOME (12) =====
  {
    id: "p_lego_orchid",
    title: "Конструктор LEGO Icons «Орхидея» 10311",
    brand: "LEGO",
    storeId: "mirkubikov",
    storeUrl: "https://mir-kubikov.ru/catalog/detail.php?ID=14210",
    price: 699900,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
    color: "#d4b0ff",
    tags: ["608 деталей"],
    description: "Собранная вручную орхидея, которая никогда не завянет. Тихий акцент на полку или подоконник.",
  },
  {
    id: "p_laric_diffuser",
    title: "Аромадиффузор La Ric «Инжир и молочай»",
    brand: "La Ric",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=%D0%B0%D1%80%D0%BE%D0%BC%D0%B0%D0%B4%D0%B8%D1%84%D1%84%D1%83%D0%B7%D0%BE%D1%80+la+ric",
    price: 199000,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1598900438360-1c5b8a0fd0d9?auto=format&fit=crop&w=1200&q=80",
    color: "#ede6da",
    tags: ["120 мл"],
    description: "Тёплый инжирный аромат на два месяца фоновой работы. Хорошо встаёт в прихожей и на рабочем столе.",
  },
  {
    id: "p_hoff_table",
    title: "Прикроватный столик Hoff Ergo, дуб",
    brand: "Hoff",
    storeId: "hoff",
    storeUrl: "https://hoff.ru/search/?q=%D0%BF%D1%80%D0%B8%D0%BA%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D0%BD%D1%8B%D0%B9+%D1%81%D1%82%D0%BE%D0%BB%D0%B8%D0%BA",
    price: 849000,
    originalPrice: 1099000,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80",
    color: "#b9a389",
    tags: ["Дуб сонома"],
    description: "Небольшой столик-спутник для чашки кофе и книги. Собирается за пятнадцать минут и не мешается.",
  },
  {
    id: "p_hoff_sofa",
    title: "Диван-кровать прямой Hoff Melia, велюр",
    brand: "Hoff",
    storeId: "hoff",
    storeUrl: "https://hoff.ru/search/?q=%D0%B4%D0%B8%D0%B2%D0%B0%D0%BD+melia",
    price: 3999000,
    originalPrice: 4999000,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80",
    color: "#7a8070",
    tags: ["Еврокнижка"],
    description: "Глубокий велюровый диван с механикой «еврокнижка». Разворачивается в просторное спальное место.",
  },
  {
    id: "p_kitfort_vacuum",
    title: "Робот-пылесос Kitfort KT-5116",
    brand: "Kitfort",
    storeId: "citilink",
    storeUrl: "https://www.citilink.ru/search/?text=kitfort+kt-5116",
    price: 1699000,
    originalPrice: 2199000,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1626436819821-d2cbfe3bb6f1?auto=format&fit=crop&w=1200&q=80",
    color: "#151515",
    tags: ["Сухая + влажная"],
    description: "Моет пол, пылесосит и умеет обходить провода. Управляется через приложение.",
  },
  {
    id: "p_dyson_v8",
    title: "Беспроводной пылесос Dyson V8 Absolute",
    brand: "Dyson",
    storeId: "dns",
    storeUrl: "https://www.dns-shop.ru/search/?q=dyson+v8",
    price: 3499900,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&w=1200&q=80",
    color: "#5a3e90",
    tags: ["40 мин", "HEPA"],
    description: "Лёгкий ручной пылесос с HEPA‑фильтрацией. Сорок минут автономки хватает на всю квартиру.",
  },
  {
    id: "p_xiaomi_humidifier",
    title: "Увлажнитель воздуха Xiaomi Smart Humidifier 2",
    brand: "Xiaomi",
    storeId: "citilink",
    storeUrl: "https://www.citilink.ru/search/?text=xiaomi+smart+humidifier+2",
    price: 499000,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1598902108854-10e335adac99?auto=format&fit=crop&w=1200&q=80",
    color: "#ffffff",
    tags: ["4.5 л", "Умный дом"],
    description: "Тихий ультразвук на ночь и управление через Mi Home. Бак на полный световой день.",
  },
  {
    id: "p_xiaomi_air_purifier",
    title: "Очиститель воздуха Xiaomi Smart Air Purifier 4",
    brand: "Xiaomi",
    storeId: "citilink",
    storeUrl: "https://www.citilink.ru/search/?text=xiaomi+smart+air+purifier+4",
    price: 1399000,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1614461637146-96097e6a6a5b?auto=format&fit=crop&w=1200&q=80",
    color: "#f0f0f0",
    tags: ["HEPA H13"],
    description: "Берёт на себя аллергены и городскую пыль. Достаточно один раз поставить в спальню.",
  },
  {
    id: "p_ikea_frakta",
    title: "Полка-стеллаж Divano Kallax, 4×4",
    brand: "IKEA",
    storeId: "ikea",
    storeUrl: "https://www.divano.ru/search?q=kallax",
    price: 1299000,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1600210492493-0946911123ea?auto=format&fit=crop&w=1200&q=80",
    color: "#e7dccd",
    tags: ["16 ячеек"],
    description: "Бесконечный стеллаж, в который помещается всё — книги, винил, коробки из‑под AirPods.",
  },
  {
    id: "p_philips_lamp",
    title: "Настольная лампа с гибкой ножкой, сталь",
    brand: "Xiaomi",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=xiaomi+%D0%BD%D0%B0%D1%81%D1%82%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F+%D0%BB%D0%B0%D0%BC%D0%BF%D0%B0",
    price: 349900,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80",
    color: "#1c1c1c",
    tags: ["Регулировка"],
    description: "Приятная глазу настольная лампа с плавной регулировкой. Удобно подставить к клавиатуре.",
  },
  {
    id: "p_bedsheet_seven",
    title: "Комплект постельного белья сатин, евро",
    brand: "Sofi De Marko",
    storeId: "wb",
    storeUrl: "https://www.wildberries.ru/catalog/0/search.aspx?search=sofi+de+marko+%D0%B5%D0%B2%D1%80%D0%BE+%D1%81%D0%B0%D1%82%D0%B8%D0%BD",
    price: 399000,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1200&q=80",
    color: "#efe5dc",
    tags: ["Сатин"],
    description: "Плотный 100% хлопок, приятный на ощупь. Работает как маленькая операция «перезапуск недели».",
  },
  {
    id: "p_towel_cawo",
    title: "Махровое полотенце Cawo, 70×140 см",
    brand: "Cawo",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=cawo+%D0%BF%D0%BE%D0%BB%D0%BE%D1%82%D0%B5%D0%BD%D1%86%D0%B5",
    price: 249000,
    categoryId: "home",
    image: "https://images.unsplash.com/photo-1519791883288-dc8bd696e667?auto=format&fit=crop&w=1200&q=80",
    color: "#d7e0d8",
    tags: ["500 г/м²"],
    description: "Немецкое махровое, плотное и очень мягкое. То самое «отельное» ощущение после душа.",
  },

  // ===== BEAUTY (10) =====
  {
    id: "p_dyson_airwrap",
    title: "Стайлер Dyson Airwrap Complete Long",
    brand: "Dyson",
    storeId: "goldapple",
    storeUrl: "https://goldapple.ru/search?q=dyson+airwrap",
    price: 6499000,
    categoryId: "beauty",
    image: "https://images.unsplash.com/photo-1522335789203-aaa5f1c9b087?auto=format&fit=crop&w=1200&q=80",
    color: "#c8afff",
    tags: ["Coanda"],
    description: "Сушит, завивает, выпрямляет и приподнимает у корней — воздухом, а не экстремальным нагревом.",
  },
  {
    id: "p_laneige_mask",
    title: "Ночная маска для губ Laneige — Berry",
    brand: "Laneige",
    storeId: "goldapple",
    storeUrl: "https://goldapple.ru/search?q=laneige+lip+sleeping+mask",
    price: 229000,
    categoryId: "beauty",
    image: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=1200&q=80",
    color: "#f6bfcf",
    tags: ["На ночь"],
    description: "Ягодная маска с витамином C. К утру губы выглядят так, будто вы спали восемь часов.",
  },
  {
    id: "p_letique_lip",
    title: "Бальзам для губ Letique Nude Kiss",
    brand: "Letique Cosmetics",
    storeId: "goldapple",
    storeUrl: "https://goldapple.ru/search?q=letique",
    price: 89000,
    categoryId: "beauty",
    image: "https://images.unsplash.com/photo-1631730486572-226d1f595b68?auto=format&fit=crop&w=1200&q=80",
    color: "#c79271",
    tags: ["Vegan"],
    description: "Лёгкий питательный бальзам с маслом ши — приятный карамельный оттенок и никакого блеска.",
  },
  {
    id: "p_cerave_cream",
    title: "Увлажняющий крем CeraVe Moisturising Cream, 340 мл",
    brand: "CeraVe",
    storeId: "goldapple",
    storeUrl: "https://goldapple.ru/search?q=cerave",
    price: 159000,
    categoryId: "beauty",
    image: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=1200&q=80",
    color: "#ffffff",
    tags: ["Церамиды"],
    description: "Большая банка крема с тремя видами церамид. Работает на лице, руках и локтях — везде.",
  },
  {
    id: "p_missha_bb",
    title: "BB-крем Missha Perfect Cover SPF42",
    brand: "Missha",
    storeId: "goldapple",
    storeUrl: "https://goldapple.ru/search?q=missha+perfect+cover",
    price: 139000,
    categoryId: "beauty",
    image: "https://images.unsplash.com/photo-1522335789203-aaa5f1c9b087?auto=format&fit=crop&w=1200&q=80",
    color: "#e8c8a3",
    tags: ["SPF 42"],
    description: "Тот самый корейский BB, что вывел категорию. Покрывает и защищает от солнца одновременно.",
  },
  {
    id: "p_beautyblender",
    title: "Спонж для макияжа beautyblender Original",
    brand: "beautyblender",
    storeId: "letoile",
    storeUrl: "https://www.letu.ru/search?text=beautyblender",
    price: 199000,
    categoryId: "beauty",
    image: "https://images.unsplash.com/photo-1487412840807-1c9cba14d1e8?auto=format&fit=crop&w=1200&q=80",
    color: "#ff6ea0",
    tags: ["Многоразовый"],
    description: "Розовое яйцо, которое заменяет собой целый набор кистей. Мокрое — мягче, чем сухое.",
  },
  {
    id: "p_cannacare",
    title: "Парфюмерная вода Chloé Signature EDP 75 мл",
    brand: "Chloé",
    storeId: "letoile",
    storeUrl: "https://www.letu.ru/search?text=chloe+signature",
    price: 1299000,
    categoryId: "beauty",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=80",
    color: "#f7d9c4",
    tags: ["Пион", "Фрезия"],
    description: "Пудровый цветочный аромат — тёплый, спокойный, узнаётся за пять метров.",
  },
  {
    id: "p_electric_toothbrush",
    title: "Электрическая зубная щётка Oral-B Pro 3",
    brand: "Oral-B",
    storeId: "dns",
    storeUrl: "https://www.dns-shop.ru/search/?q=oral-b+pro+3",
    price: 599000,
    originalPrice: 799000,
    categoryId: "beauty",
    image: "https://images.unsplash.com/photo-1559591937-abc3a5d4a39d?auto=format&fit=crop&w=1200&q=80",
    color: "#d8d8d8",
    tags: ["3 режима"],
    description: "Давление, таймер, две недели автономки. Заметно экономит время в ванной.",
  },
  {
    id: "p_diptyque_candle",
    title: "Ароматическая свеча Baies Diptyque, 190 г",
    brand: "Diptyque",
    storeId: "goldapple",
    storeUrl: "https://goldapple.ru/search?q=diptyque+baies",
    price: 989000,
    categoryId: "beauty",
    image: "https://images.unsplash.com/photo-1608181831732-a56eed4a6fa9?auto=format&fit=crop&w=1200&q=80",
    color: "#e7d6b7",
    tags: ["190 г"],
    description: "Самая популярная свеча Diptyque — чёрная смородина, роза и немного болгарских каникул.",
  },
  {
    id: "p_estel_professional",
    title: "Шампунь для волос Estel Otium Unique, 250 мл",
    brand: "Estel",
    storeId: "ym",
    storeUrl: "https://market.yandex.ru/search?text=estel+otium+unique",
    price: 69000,
    categoryId: "beauty",
    image: "https://images.unsplash.com/photo-1590439471364-192aa70c0b53?auto=format&fit=crop&w=1200&q=80",
    color: "#e8f0ff",
    tags: ["Профессиональный"],
    description: "Российский профессиональный бренд. Хорошо моет, не скрипит, не спорит с балаяжем.",
  },

  // ===== BOOKS (10) =====
  {
    id: "p_moleskine",
    title: "Блокнот Moleskine Classic Large, точка",
    brand: "Moleskine",
    storeId: "podpisnie",
    storeUrl: "https://podpisnie.ru/search/?q=moleskine",
    price: 249000,
    categoryId: "books",
    image: "https://images.unsplash.com/photo-1531346680769-a1d79b57de5c?auto=format&fit=crop&w=1200&q=80",
    color: "#222",
    tags: ["240 стр.", "Точка"],
    description: "240 страниц цвета слоновой кости, резинка и кармашек сзади — как у всех приличных людей.",
  },
  {
    id: "p_atomic_habits",
    title: "Книга «Атомные привычки» — Джеймс Клир",
    brand: "Эксмо",
    storeId: "chitaigorod",
    storeUrl: "https://www.chitai-gorod.ru/search?phrase=%D0%B0%D1%82%D0%BE%D0%BC%D0%BD%D1%8B%D0%B5+%D0%BF%D1%80%D0%B8%D0%B2%D1%8B%D1%87%D0%BA%D0%B8",
    price: 79000,
    originalPrice: 109000,
    categoryId: "books",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80",
    color: "#eee3cf",
    tags: ["Твёрдый переплёт"],
    description: "Небольшие шаги, которые правда работают. Книга, которую в офисе подарили все всем.",
  },
  {
    id: "p_manson_book",
    title: "Книга «Тонкое искусство пофигизма» — Марк Мэнсон",
    brand: "Альпина Паблишер",
    storeId: "chitaigorod",
    storeUrl:
      "https://www.chitai-gorod.ru/search?phrase=%D1%82%D0%BE%D0%BD%D0%BA%D0%BE%D0%B5+%D0%B8%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%BE+%D0%BF%D0%BE%D1%84%D0%B8%D0%B3%D0%B8%D0%B7%D0%BC%D0%B0",
    price: 69000,
    categoryId: "books",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80",
    color: "#ffdd55",
    tags: ["Бестселлер"],
    description: "Про то, как выбирать, ради чего стоит волноваться — и честно признаваться, ради чего нет.",
  },
  {
    id: "p_sapiens_book",
    title: "Книга «Sapiens. Краткая история человечества» — Ю.Н. Харари",
    brand: "Синдбад",
    storeId: "labirint",
    storeUrl: "https://www.labirint.ru/search/sapiens/",
    price: 89000,
    categoryId: "books",
    image: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=1200&q=80",
    color: "#bfb4a0",
    tags: ["Научпоп"],
    description: "Короткая и дерзкая история Homo sapiens. Подойдёт и тем, кто «не любит истории».",
  },
  {
    id: "p_ishiguro_book",
    title: "Книга «Клара и Солнце» — Кадзуо Исигуро",
    brand: "Эксмо",
    storeId: "podpisnie",
    storeUrl: "https://podpisnie.ru/search/?q=%D0%BA%D0%BB%D0%B0%D1%80%D0%B0+%D0%B8+%D1%81%D0%BE%D0%BB%D0%BD%D1%86%D0%B5",
    price: 64900,
    categoryId: "books",
    image: "https://images.unsplash.com/photo-1531988042231-d39a9cc12a9a?auto=format&fit=crop&w=1200&q=80",
    color: "#f0d88f",
    tags: ["Нобелевка"],
    description: "Тихий, очень человеческий роман о роботе-компаньоне и солнце. Исигуро не умеет писать плохо.",
  },
  {
    id: "p_bradbury_451",
    title: "Книга «451° по Фаренгейту» — Рэй Брэдбери",
    brand: "Эксмо",
    storeId: "chitaigorod",
    storeUrl: "https://www.chitai-gorod.ru/search?phrase=451+%D0%BF%D0%BE+%D1%84%D0%B0%D1%80%D0%B5%D0%BD%D0%B3%D0%B5%D0%B9%D1%82%D1%83",
    price: 44900,
    categoryId: "books",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=1200&q=80",
    color: "#d8310f",
    tags: ["Классика"],
    description: "Вещь, которая стареет только красивее. Читается за выходные, остаётся навсегда.",
  },
  {
    id: "p_master_margarita",
    title: "Книга «Мастер и Маргарита» — Михаил Булгаков",
    brand: "АСТ",
    storeId: "respublika",
    storeUrl: "https://www.respublica.ru/search?q=%D0%BC%D0%B0%D1%81%D1%82%D0%B5%D1%80+%D0%B8+%D0%BC%D0%B0%D1%80%D0%B3%D0%B0%D1%80%D0%B8%D1%82%D0%B0",
    price: 69900,
    categoryId: "books",
    image: "https://images.unsplash.com/photo-1455885661740-29cbf08a42fa?auto=format&fit=crop&w=1200&q=80",
    color: "#3a2a1f",
    tags: ["Классика"],
    description: "Роман, который можно перечитывать каждые пять лет и находить в нём новую книгу.",
  },
  {
    id: "p_bookshelf_helper",
    title: "Книжная закладка кожаная с монограммой",
    brand: "Подписные издания",
    storeId: "podpisnie",
    storeUrl: "https://podpisnie.ru/search/?q=%D0%B7%D0%B0%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0",
    price: 79000,
    categoryId: "books",
    image: "https://images.unsplash.com/photo-1491841651911-c44c30c34548?auto=format&fit=crop&w=1200&q=80",
    color: "#6e3a1d",
    tags: ["Кожа"],
    description: "Маленький повод лишний раз зайти в книжный. Натуральная кожа и монограмма по выбору.",
  },
  {
    id: "p_sketchbook",
    title: "Скетчбук А5, плотная бумага, Moleskine Art",
    brand: "Moleskine",
    storeId: "podpisnie",
    storeUrl: "https://podpisnie.ru/search/?q=moleskine+art",
    price: 149000,
    categoryId: "books",
    image: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=1200&q=80",
    color: "#e8e2d4",
    tags: ["200 г/м²"],
    description: "Бумага, которой не страшны ни маркеры, ни акварель. Приятно даже просто листать.",
  },
  {
    id: "p_reading_lamp",
    title: "Лампа для чтения с прищепкой, USB",
    brand: "Xiaomi",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=xiaomi+%D0%BB%D0%B0%D0%BC%D0%BF%D0%B0+%D0%B4%D0%BB%D1%8F+%D1%87%D1%82%D0%B5%D0%BD%D0%B8%D1%8F",
    price: 89000,
    categoryId: "books",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80",
    color: "#1c1c1c",
    tags: ["Прищепка"],
    description: "Цепляется к книге или к изголовью. Мягкий тёплый свет, три уровня яркости.",
  },

  // ===== OUTDOORS (12) =====
  {
    id: "p_stanley_quencher",
    title: "Термокружка Stanley Quencher H2.0 0.9 л",
    brand: "Stanley",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=stanley+quencher+h2.0+0.9",
    price: 499000,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1625708458528-802ec79b1ed8?auto=format&fit=crop&w=1200&q=80",
    color: "#e9cfc2",
    tags: ["Влезает в подстаканник"],
    description: "Та самая тамблер‑кружка из TikTok: двойная стенка, соломинка и 24 часа холода.",
  },
  {
    id: "p_contigo_bottle",
    title: "Термобутылка Contigo Autoseal West Loop 0.47 л",
    brand: "Contigo",
    storeId: "sportmaster",
    storeUrl: "https://www.sportmaster.ru/search/?q=contigo+west+loop",
    price: 249900,
    originalPrice: 299900,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1200&q=80",
    color: "#2f5d8a",
    tags: ["Autoseal"],
    description: "Кнопка Autoseal — и ни капли мимо. Держит кофе горячим до 5 часов.",
  },
  {
    id: "p_outventure_down",
    title: "Пуховик женский Outventure Ultra Light",
    brand: "Outventure",
    storeId: "sportmaster",
    storeUrl:
      "https://www.sportmaster.ru/search/?q=outventure+%D0%BF%D1%83%D1%85%D0%BE%D0%B2%D0%B8%D0%BA",
    price: 499900,
    originalPrice: 699900,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1548883354-94bcfe321cbb?auto=format&fit=crop&w=1200&q=80",
    color: "#0f1b2d",
    tags: ["Компактный"],
    description: "Лёгкий пуховик, который складывается в собственный мешочек. Секрет городского путешественника.",
  },
  {
    id: "p_columbia_powder",
    title: "Куртка мужская Columbia Powder Lite",
    brand: "Columbia",
    storeId: "sportmaster",
    storeUrl: "https://www.sportmaster.ru/search/?q=columbia+powder+lite",
    price: 1299900,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=80",
    color: "#2b4f2b",
    tags: ["Omni-Heat"],
    description: "Тёплая синтетика с отражающей подкладкой Omni‑Heat. От ноября до марта как родная.",
  },
  {
    id: "p_naturehike_tent",
    title: "Палатка Naturehike Cloud-Up 2, двухместная",
    brand: "Naturehike",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=naturehike+cloud+up+2",
    price: 1199000,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80",
    color: "#ffb23a",
    tags: ["1.9 кг", "20D"],
    description: "Двухслойная палатка на двоих весом меньше двух килограмм. Сборка с закрытыми глазами.",
  },
  {
    id: "p_black_diamond_headlamp",
    title: "Налобный фонарь Black Diamond Spot 400",
    brand: "Black Diamond",
    storeId: "ym",
    storeUrl: "https://market.yandex.ru/search?text=black+diamond+spot+400",
    price: 399000,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1501179691627-eeaa65ea017c?auto=format&fit=crop&w=1200&q=80",
    color: "#1d1d1d",
    tags: ["IPX8", "400 лм"],
    description: "Серьёзный фонарь на 400 люмен, водонепроницаемый, с красным режимом. Классика для тех, кто ходит.",
  },
  {
    id: "p_yeti_cooler",
    title: "Термобокс Igloo Maxcold 30 л",
    brand: "Igloo",
    storeId: "sportmaster",
    storeUrl: "https://www.sportmaster.ru/search/?q=igloo+maxcold+30",
    price: 599900,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?auto=format&fit=crop&w=1200&q=80",
    color: "#b6d2cf",
    tags: ["5 дней холода"],
    description: "Большой сумка-бокс: лёд в нём не тает сутками даже в плюс 30. Катается на дачу и на море.",
  },
  {
    id: "p_nike_metcon",
    title: "Кроссовки для зала Nike Metcon 9",
    brand: "Nike",
    storeId: "sportmaster",
    storeUrl: "https://www.sportmaster.ru/search/?q=nike+metcon",
    price: 1199000,
    originalPrice: 1499000,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1200&q=80",
    color: "#111",
    tags: ["Кроссфит"],
    description: "Плоская подошва для тяг и амортизация для бёрпи. Обувь для любой функциональной тренировки.",
  },
  {
    id: "p_garmin_fenix",
    title: "Умные часы Garmin Fenix 7 Sapphire Solar",
    brand: "Garmin",
    storeId: "dns",
    storeUrl: "https://www.dns-shop.ru/search/?q=garmin+fenix+7",
    price: 8999000,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=1200&q=80",
    color: "#3a3a3a",
    tags: ["Solar", "GPS"],
    description: "Автономность в неделях и реально подробные карты. Часы, с которыми ходят на К2 и в офис.",
  },
  {
    id: "p_yoga_mat",
    title: "Коврик для йоги Demix ProYoga 6 мм",
    brand: "Demix",
    storeId: "sportmaster",
    storeUrl: "https://www.sportmaster.ru/search/?q=demix+%D0%BA%D0%BE%D0%B2%D1%80%D0%B8%D0%BA+%D0%B4%D0%BB%D1%8F+%D0%B9%D0%BE%D0%B3%D0%B8",
    price: 169900,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80",
    color: "#8a76c9",
    tags: ["6 мм"],
    description: "Мягкий шестимиллиметровый коврик, не скользит под ладонями. Сворачивается в аккуратный рулон.",
  },
  {
    id: "p_trekking_poles",
    title: "Трекинговые палки Naturehike ST05, пара",
    brand: "Naturehike",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=naturehike+%D1%82%D1%80%D0%B5%D0%BA%D0%B8%D0%BD%D0%B3%D0%BE%D0%B2%D1%8B%D0%B5+%D0%BF%D0%B0%D0%BB%D0%BA%D0%B8",
    price: 349000,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1544198365-f5d60b6d8190?auto=format&fit=crop&w=1200&q=80",
    color: "#3d3d3d",
    tags: ["Алюминий"],
    description: "Лёгкие и крепкие алюминиевые палки с пробковой ручкой. Раскладываются в три секции.",
  },
  {
    id: "p_backpack_deuter",
    title: "Рюкзак Deuter Aircontact Core 35+10 л",
    brand: "Deuter",
    storeId: "sportmaster",
    storeUrl: "https://www.sportmaster.ru/search/?q=deuter+aircontact",
    price: 1499000,
    categoryId: "outdoors",
    image: "https://images.unsplash.com/photo-1592878904946-b3cd8ae243d0?auto=format&fit=crop&w=1200&q=80",
    color: "#19466b",
    tags: ["Пояс", "35+10 л"],
    description: "Отличная подвеска для долгих переходов. Снимаемый клапан и отдельный вход в нижний отсек.",
  },

  // ===== KITCHEN (12) =====
  {
    id: "p_lodge_cast_iron",
    title: "Чугунная сковорода Lodge 26 см с ручкой",
    brand: "Lodge",
    storeId: "ozon",
    storeUrl:
      "https://www.ozon.ru/search/?text=lodge+%D1%87%D1%83%D0%B3%D1%83%D0%BD%D0%BD%D0%B0%D1%8F+%D1%81%D0%BA%D0%BE%D0%B2%D0%BE%D1%80%D0%BE%D0%B4%D0%B0",
    price: 599000,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    color: "#1b1b1b",
    tags: ["Предзаводская прошивка"],
    description: "Американский литой чугун, предобработанный маслом. Переживёт вас, ваши блинчики и ремонт кухни.",
  },
  {
    id: "p_opinel_12",
    title: "Нож шеф-повара Opinel №12 с деревянной ручкой",
    brand: "Opinel",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=opinel+12+%D1%88%D0%B5%D1%84",
    price: 349000,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=1200&q=80",
    color: "#a06a3b",
    tags: ["Sandvik 12C27"],
    description: "Французская сталь Sandvik и тёплая бук-ручка. Нож, за который берутся, когда нужен один-единственный.",
  },
  {
    id: "p_aeropress",
    title: "Кофеварка AeroPress Original",
    brand: "AeroPress",
    storeId: "tastycoffee",
    storeUrl: "https://tastycoffee.ru/catalog/dlya_zavarivaniya/aeropress/",
    price: 499000,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=80",
    color: "#2e2e2e",
    tags: ["1 чашка, 1 минута"],
    description: "Культовый «поршень» для чистой чашки фильтра на офисной кухне, в поезде или на даче.",
  },
  {
    id: "p_bialetti",
    title: "Гейзерная кофеварка Bialetti Moka Express на 6 чашек",
    brand: "Bialetti",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=bialetti+moka+express+6",
    price: 399000,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784e6a?auto=format&fit=crop&w=1200&q=80",
    color: "#8a8a8a",
    tags: ["Made in Italy"],
    description: "Восьмигранная итальянская классика с 1933 года. Один щелчок пламени — и вся квартира пахнет утром.",
  },
  {
    id: "p_delonghi_dedica",
    title: "Рожковая кофемашина De'Longhi EC 685 Dedica",
    brand: "De'Longhi",
    storeId: "mvideo",
    storeUrl: "https://www.mvideo.ru/product-list-page?q=delonghi+ec+685",
    price: 2699000,
    originalPrice: 3199000,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=1200&q=80",
    color: "#c9c9c9",
    tags: ["15 бар", "15 см"],
    description: "Узкая рожковая машина под круассан и эспрессо дома. Помещается между микроволновкой и стеной.",
  },
  {
    id: "p_kitchenaid_mixer",
    title: "Планетарный миксер KitchenAid Artisan 4.8 л",
    brand: "KitchenAid",
    storeId: "mvideo",
    storeUrl: "https://www.mvideo.ru/product-list-page?q=kitchenaid+artisan",
    price: 4999000,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1598515213692-5f252f75d785?auto=format&fit=crop&w=1200&q=80",
    color: "#b31b1b",
    tags: ["10 скоростей"],
    description: "Легендарный миксер на металлическом шасси. Тесто, кремы, фарш — всё под одной крышкой.",
  },
  {
    id: "p_staub_cocotte",
    title: "Чугунная кастрюля Staub Cocotte 24 см, вишнёвая",
    brand: "Staub",
    storeId: "megamarket",
    storeUrl: "https://megamarket.ru/catalog/search/?q=staub+cocotte+24",
    price: 2999000,
    originalPrice: 3999000,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1581789093215-afac3ed20ef9?auto=format&fit=crop&w=1200&q=80",
    color: "#c2262f",
    tags: ["Эмалированный чугун"],
    description: "Самовсплывающие капли внутри крышки и та самая вишнёвая эмаль. Для супов и рагу — лучшее.",
  },
  {
    id: "p_victorinox_knife",
    title: "Нож кухонный Victorinox Swiss Classic 25 см",
    brand: "Victorinox",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=victorinox+swiss+classic",
    price: 349000,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1549049950-48d5887197a0?auto=format&fit=crop&w=1200&q=80",
    color: "#101010",
    tags: ["Швейцария"],
    description: "Рабочая швейцарская сталь и лёгкая синтетическая ручка. Режет лук так, что от него не плачут.",
  },
  {
    id: "p_le_creuset_kettle",
    title: "Чайник заварочный Le Creuset Stoneware 1.3 л",
    brand: "Le Creuset",
    storeId: "megamarket",
    storeUrl: "https://megamarket.ru/catalog/search/?q=le+creuset+stoneware",
    price: 2999000,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1509785307050-d4066910ec1e?auto=format&fit=crop&w=1200&q=80",
    color: "#2a3e66",
    tags: ["Каменная керамика"],
    description: "Плотная каменная керамика, не впитывает запахи, красиво стоит на столе. Большой чайник для гостей.",
  },
  {
    id: "p_hario_v60",
    title: "Воронка Hario V60-02 керамика, белая",
    brand: "Hario",
    storeId: "tastycoffee",
    storeUrl: "https://tastycoffee.ru/catalog/dlya_zavarivaniya/hario-v60/",
    price: 149000,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?auto=format&fit=crop&w=1200&q=80",
    color: "#ffffff",
    tags: ["Керамика"],
    description: "Классика для фильтра. Спиральные ребра внутри воронки — для правильного экстракта.",
  },
  {
    id: "p_coffee_grinder",
    title: "Кофемолка жерновая Timemore Chestnut C2",
    brand: "Timemore",
    storeId: "tastycoffee",
    storeUrl: "https://tastycoffee.ru/catalog/kofemolki/",
    price: 799000,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1200&q=80",
    color: "#0e0e0e",
    tags: ["Жернова E&B"],
    description: "Ручная кофемолка с отличными жерновами. Для фильтра и эспрессо, всё в одной крутилке.",
  },
  {
    id: "p_muji_kettle",
    title: "Электрочайник Redmond RK-G1414 1.7 л",
    brand: "Redmond",
    storeId: "citilink",
    storeUrl: "https://www.citilink.ru/search/?text=redmond+rk-g1414",
    price: 249900,
    categoryId: "kitchen",
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=1200&q=80",
    color: "#bebebe",
    tags: ["1.7 л", "Стекло"],
    description: "Стеклянный чайник со строкой подсветки. Быстро кипятит и вписывается в любую кухню.",
  },

  // ===== MUSIC (10) =====
  {
    id: "p_at_turntable",
    title: "Виниловый проигрыватель Audio-Technica AT-LP60X",
    brand: "Audio-Technica",
    storeId: "pult",
    storeUrl: "https://www.pult.ru/catalog/vinilovie-proigrivateli/audio-technica-at-lp60x",
    price: 1999000,
    categoryId: "music",
    image: "https://images.unsplash.com/photo-1542456882-6bebfd3d0a44?auto=format&fit=crop&w=1200&q=80",
    color: "#0e0e0e",
    tags: ["Автомат", "33/45"],
    description: "Автоматический вертак с готовым фонокорректором. Достал из коробки, поставил пластинку — играет.",
  },
  {
    id: "p_sberboom",
    title: "Умная колонка SberBoom (с Салютом)",
    brand: "Сбер",
    storeId: "megamarket",
    storeUrl: "https://megamarket.ru/catalog/details/sberboom/",
    price: 1499900,
    originalPrice: 1799900,
    categoryId: "music",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1200&q=80",
    color: "#0b0b0b",
    tags: ["Салют", "90 Вт"],
    description: "Большая колонка с мощным басом и тремя виртуальными ассистентами. Дома звучит как небольшой клуб.",
  },
  {
    id: "p_jbl_flip",
    title: "Портативная колонка JBL Flip 6",
    brand: "JBL",
    storeId: "dns",
    storeUrl: "https://www.dns-shop.ru/search/?q=jbl+flip+6",
    price: 999000,
    originalPrice: 1299900,
    categoryId: "music",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1200&q=80",
    color: "#101820",
    tags: ["IP67", "12 ч"],
    description: "Водонепроницаемая, с честным басом и 12 часами автономки. Катается с вами на пляж и в горы.",
  },
  {
    id: "p_fender_guitar",
    title: "Электрогитара Squier Affinity Stratocaster",
    brand: "Fender",
    storeId: "pult",
    storeUrl: "https://www.pult.ru/catalog/elektrogitary/",
    price: 3999000,
    categoryId: "music",
    image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=1200&q=80",
    color: "#c2262f",
    tags: ["Stratocaster"],
    description: "Самый удобный Strat за вменяемые деньги. Быстрый кленовый гриф и три сингла.",
  },
  {
    id: "p_yamaha_keyboard",
    title: "Цифровое пианино Yamaha P-45",
    brand: "Yamaha",
    storeId: "pult",
    storeUrl: "https://www.pult.ru/catalog/cifrovye-pianino/",
    price: 4599000,
    categoryId: "music",
    image: "https://images.unsplash.com/photo-1520166012956-add9ba0835cb?auto=format&fit=crop&w=1200&q=80",
    color: "#1e1e1e",
    tags: ["88 клавиш", "GHS"],
    description: "Честная взвешенная механика и 10 базовых звуков. Начальная точка, которой хватает надолго.",
  },
  {
    id: "p_ukulele_mahalo",
    title: "Укулеле сопрано Mahalo Rainbow Blue",
    brand: "Mahalo",
    storeId: "pult",
    storeUrl: "https://www.pult.ru/catalog/ukulele/",
    price: 349000,
    categoryId: "music",
    image: "https://images.unsplash.com/photo-1525201548942-d8732f6617a0?auto=format&fit=crop&w=1200&q=80",
    color: "#3d6fb8",
    tags: ["Сопрано"],
    description: "Яркое пластиково‑деревянное укулеле, на котором через неделю уже получается «Over the Rainbow».",
  },
  {
    id: "p_vinyl_queen",
    title: "Виниловая пластинка Queen — Greatest Hits (2 LP)",
    brand: "Virgin EMI",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=queen+greatest+hits+vinyl+2+lp",
    price: 429000,
    categoryId: "music",
    image: "https://images.unsplash.com/photo-1495707902641-75cac588d2e9?auto=format&fit=crop&w=1200&q=80",
    color: "#ffd15a",
    tags: ["2 LP"],
    description: "Вся золотая середина Queen на двух пластинках ремастер 2011 года. Идеально, чтобы обживать вертак.",
  },
  {
    id: "p_vinyl_daft_punk",
    title: "Виниловая пластинка Daft Punk — Random Access Memories (2 LP)",
    brand: "Sony Music",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=daft+punk+random+access+memories+vinyl",
    price: 549900,
    categoryId: "music",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80",
    color: "#c2a15a",
    tags: ["2 LP", "180 г"],
    description: "Взрослый, тёплый и очень виниловый альбом. Два диска, толстый картон, всё как надо.",
  },
  {
    id: "p_headphone_stand",
    title: "Подставка для наушников Klipsch HP Stand",
    brand: "Klipsch",
    storeId: "pult",
    storeUrl: "https://www.pult.ru/catalog/podstavki-dlya-naushnikov/",
    price: 349000,
    categoryId: "music",
    image: "https://images.unsplash.com/photo-1590658006821-04f4008d5717?auto=format&fit=crop&w=1200&q=80",
    color: "#0a0a0a",
    tags: ["Металл"],
    description: "Стальная подставка с мягким седлом. Чистит рабочий стол одним появлением.",
  },
  {
    id: "p_marantz_amp",
    title: "Стереоусилитель Marantz PM6007",
    brand: "Marantz",
    storeId: "pult",
    storeUrl: "https://www.pult.ru/catalog/usiliteli/marantz-pm6007",
    price: 6999000,
    categoryId: "music",
    image: "https://images.unsplash.com/photo-1605036519403-2b3c8c2aba5c?auto=format&fit=crop&w=1200&q=80",
    color: "#2d2d2d",
    tags: ["MM фонокор."],
    description: "Тёплый, музыкальный усилитель с фонокорректором на борту. Идеальная пара к виниловому вертаку.",
  },

  // ===== KIDS (9) =====
  {
    id: "p_lego_city",
    title: "Конструктор LEGO City «Центр города» 60380",
    brand: "LEGO",
    storeId: "mirkubikov",
    storeUrl: "https://mir-kubikov.ru/catalog/index.php?q=city+60380",
    price: 1599000,
    categoryId: "kids",
    image: "https://images.unsplash.com/photo-1558877385-8c1c3c9b3a0a?auto=format&fit=crop&w=1200&q=80",
    color: "#f2c94c",
    tags: ["6+", "2000 дет."],
    description: "Большая городская сцена с магазином, пиццерией, салоном красоты и десятком минифигурок.",
  },
  {
    id: "p_lego_botanical",
    title: "Конструктор LEGO Icons «Букет цветов» 10280",
    brand: "LEGO",
    storeId: "mirkubikov",
    storeUrl: "https://mir-kubikov.ru/catalog/index.php?q=10280",
    price: 799000,
    categoryId: "kids",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
    color: "#ffb6c1",
    tags: ["18+", "Декор"],
    description: "Букет из лего-цветов, которые не требуют вазы. Отличный подарок тем, кто устал от настоящих роз.",
  },
  {
    id: "p_kapla_wooden",
    title: "Конструктор деревянный KAPLA, 200 деталей",
    brand: "KAPLA",
    storeId: "mytoys",
    storeUrl: "https://www.mytoys.ru/search/?search=kapla",
    price: 999000,
    categoryId: "kids",
    image: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=1200&q=80",
    color: "#d6b273",
    tags: ["Сосна", "3+"],
    description: "Безумно простой и одновременно бесконечный конструктор. Из одних палочек — крепость, мост, динозавр.",
  },
  {
    id: "p_barbie_dreamhouse",
    title: "Дом для кукол Barbie DreamHouse",
    brand: "Barbie",
    storeId: "detmir",
    storeUrl: "https://www.detmir.ru/search/?q=barbie+dreamhouse",
    price: 1999000,
    originalPrice: 2499000,
    categoryId: "kids",
    image: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?auto=format&fit=crop&w=1200&q=80",
    color: "#ff8ab3",
    tags: ["3 этажа"],
    description: "Трёхэтажный дом с лифтом, подсветкой и горкой. Для тех, кто точно знает, чем заняться на каникулах.",
  },
  {
    id: "p_kidizoom",
    title: "Детский фотоаппарат VTech KidiZoom Duo 5.0",
    brand: "VTech",
    storeId: "detmir",
    storeUrl: "https://www.detmir.ru/search/?q=kidizoom+duo",
    price: 599000,
    categoryId: "kids",
    image: "https://images.unsplash.com/photo-1495707902641-75cac588d2e9?auto=format&fit=crop&w=1200&q=80",
    color: "#ff66a1",
    tags: ["Две камеры"],
    description: "Противоударный фотоаппарат с играми и эффектами. Отлично переживает падения с дивана.",
  },
  {
    id: "p_puzzle_ravensburger",
    title: "Пазл Ravensburger «Карта мира», 1500 деталей",
    brand: "Ravensburger",
    storeId: "mytoys",
    storeUrl: "https://www.mytoys.ru/search/?search=ravensburger+1500",
    price: 349000,
    categoryId: "kids",
    image: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&w=1200&q=80",
    color: "#2b4e74",
    tags: ["1500 дет."],
    description: "Плотный картон, идеальная посадка, честная картография. Отличный проект на длинные выходные.",
  },
  {
    id: "p_scooter_micro",
    title: "Самокат Micro Maxi Deluxe LED",
    brand: "Micro",
    storeId: "detmir",
    storeUrl: "https://www.detmir.ru/search/?q=micro+maxi+deluxe",
    price: 1299000,
    originalPrice: 1599000,
    categoryId: "kids",
    image: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&w=1200&q=80",
    color: "#5abec1",
    tags: ["5-12 лет"],
    description: "Самый надёжный детский самокат на наших тротуарах. Колёса со светом, складная рулевая.",
  },
  {
    id: "p_board_monopoly",
    title: "Настольная игра Monopoly «Классическая»",
    brand: "Hasbro",
    storeId: "detmir",
    storeUrl: "https://www.detmir.ru/search/?q=monopoly",
    price: 249000,
    categoryId: "kids",
    image: "https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?auto=format&fit=crop&w=1200&q=80",
    color: "#c9322b",
    tags: ["4+ игрока"],
    description: "Та самая Monopoly. Два часа веселья — и стабильно один обидевшийся двоюродный брат.",
  },
  {
    id: "p_board_catan",
    title: "Настольная игра «Катан»",
    brand: "Hobby World",
    storeId: "mytoys",
    storeUrl: "https://www.mytoys.ru/search/?search=%D0%BA%D0%B0%D1%82%D0%B0%D0%BD",
    price: 349000,
    categoryId: "kids",
    image: "https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?auto=format&fit=crop&w=1200&q=80",
    color: "#d8b06e",
    tags: ["3-4 игрока"],
    description: "Немецкая настольная классика. Стратегия, переговоры и бесконечные «ты мне дорогу через деревню».",
  },

  // ===== GAMING (10) =====
  {
    id: "p_ps5_slim",
    title: "Игровая консоль Sony PlayStation 5 Slim (с дисководом)",
    brand: "Sony",
    storeId: "dns",
    storeUrl: "https://www.dns-shop.ru/search/?q=playstation+5+slim",
    price: 5499900,
    categoryId: "gaming",
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=1200&q=80",
    color: "#fafafa",
    tags: ["1 ТБ", "4K"],
    description: "Та самая PS5, но тоньше и тише. 1 ТБ SSD, снимаемый дисковод.",
  },
  {
    id: "p_switch_oled",
    title: "Игровая приставка Nintendo Switch OLED, белая",
    brand: "Nintendo",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=nintendo+switch+oled",
    price: 3799000,
    categoryId: "gaming",
    image: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?auto=format&fit=crop&w=1200&q=80",
    color: "#f6f6f6",
    tags: ["OLED 7\""],
    description: "Сочный OLED-экран, широкая подставка и 64 ГБ памяти. Для поездов и долгих вечеров.",
  },
  {
    id: "p_xbox_series_x",
    title: "Игровая приставка Xbox Series X 1 ТБ",
    brand: "Microsoft",
    storeId: "dns",
    storeUrl: "https://www.dns-shop.ru/search/?q=xbox+series+x",
    price: 5999000,
    categoryId: "gaming",
    image: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=1200&q=80",
    color: "#0e0e0e",
    tags: ["4K 120 Гц"],
    description: "Тот самый чёрный куб с мощным GPU и Game Pass в комплекте подписок.",
  },
  {
    id: "p_steamdeck_oled",
    title: "Портативная приставка Valve Steam Deck OLED 1 ТБ",
    brand: "Valve",
    storeId: "steam",
    storeUrl: "https://store.steampowered.com/steamdeck",
    price: 7299000,
    categoryId: "gaming",
    image: "https://images.unsplash.com/photo-1640955011254-39734e60b16f?auto=format&fit=crop&w=1200&q=80",
    color: "#1a1a1a",
    tags: ["OLED", "90 Гц"],
    description: "Портативный Steam, но с OLED, большим SSD и лучшей батареей. Любимая игра — в транспорте.",
  },
  {
    id: "p_ds5_controller",
    title: "Геймпад Sony DualSense Edge",
    brand: "Sony",
    storeId: "mvideo",
    storeUrl: "https://www.mvideo.ru/product-list-page?q=dualsense+edge",
    price: 2499900,
    categoryId: "gaming",
    image: "https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=1200&q=80",
    color: "#ffffff",
    tags: ["Кастомизация"],
    description: "Премиум‑геймпад PS5 с заменяемыми стиками, настраиваемыми кнопками и собственным кейсом.",
  },
  {
    id: "p_logitech_g502",
    title: "Игровая мышь Logitech G502 X Lightspeed",
    brand: "Logitech",
    storeId: "dns",
    storeUrl: "https://www.dns-shop.ru/search/?q=logitech+g502+x+lightspeed",
    price: 1299000,
    categoryId: "gaming",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=1200&q=80",
    color: "#1a1a1a",
    tags: ["HERO 25K"],
    description: "Флагман линейки G502 без проводов. Дракон-сенсор, кнопки-гибриды и приятно тяжелые клики.",
  },
  {
    id: "p_razer_keyboard",
    title: "Игровая клавиатура Razer Huntsman V3 Pro",
    brand: "Razer",
    storeId: "citilink",
    storeUrl: "https://www.citilink.ru/search/?text=razer+huntsman+v3",
    price: 1699000,
    categoryId: "gaming",
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=80",
    color: "#0d0d0d",
    tags: ["Аналоговые"],
    description: "Оптические аналоговые переключатели с регулируемой точкой срабатывания. Экстрим для шутеров.",
  },
  {
    id: "p_nvidia_4070",
    title: "Видеокарта Palit GeForce RTX 4070 Super Dual 12 ГБ",
    brand: "Palit",
    storeId: "dns",
    storeUrl: "https://www.dns-shop.ru/search/?q=rtx+4070+super",
    price: 6499900,
    categoryId: "gaming",
    image: "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=1200&q=80",
    color: "#1b1b1b",
    tags: ["12 ГБ", "DLSS 3.5"],
    description: "Золотая середина RTX‑поколения: честные 1440p с трассировкой и DLSS на максимум.",
  },
  {
    id: "p_8bitdo_arcade",
    title: "Аркадный стик 8BitDo Arcade Stick",
    brand: "8BitDo",
    storeId: "ozon",
    storeUrl: "https://www.ozon.ru/search/?text=8bitdo+arcade+stick",
    price: 1699000,
    categoryId: "gaming",
    image: "https://images.unsplash.com/photo-1580327344181-c1163234e5a0?auto=format&fit=crop&w=1200&q=80",
    color: "#ffd24d",
    tags: ["Switch/PC"],
    description: "Настоящий аркадный стик с кнопками Kailh и подключением по Bluetooth. Для файтингов и ретро.",
  },
  {
    id: "p_corsair_headset",
    title: "Беспроводная игровая гарнитура Corsair HS80 RGB",
    brand: "Corsair",
    storeId: "citilink",
    storeUrl: "https://www.citilink.ru/search/?text=corsair+hs80+rgb",
    price: 1699000,
    originalPrice: 1999000,
    categoryId: "gaming",
    image: "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?auto=format&fit=crop&w=1200&q=80",
    color: "#0b0b0b",
    tags: ["Dolby Atmos", "20 ч"],
    description: "Флагманская беспроводная гарнитура: честный объёмный звук и микрофон, слышный в тимспике.",
  },
];
